import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises"
import { join } from "node:path"
import { afterEach, beforeEach, describe, expect, test, vi } from "vitest"
import { setCwd } from "../../src/utils/context.js"
import { runAdd } from "../../src/commands/add.js"
import { runInit } from "../../src/commands/init.js"
import { runUpdate } from "../../src/commands/update.js"
import { getRegistryTemplatePath } from "../../src/install/installer.js"
import { testCssVarPrefix as p } from "../config/prefix.js"

const generatedHeader =
  "/* Generated by @dalexto/lexsys-tokens. Do not edit directly. */"

const writeJson = async (path: string, value: unknown): Promise<void> => {
  await writeFile(path, JSON.stringify(value, null, 2) + "\n", "utf-8")
}

const writeViteConsumerFiles = async (root: string): Promise<void> => {
  await writeJson(join(root, "package.json"), {
    dependencies: {
      "@base-ui/react": "^1.4.1",
      "class-variance-authority": "^0.7.1",
      clsx: "^2.1.1",
      "tailwind-merge": "^3.5.0",
    },
    devDependencies: {
      "@tailwindcss/vite": "^4.2.4",
      tailwindcss: "^4.2.4",
    },
    packageManager: "npm@11.0.0",
  })
  await mkdir(join(root, "src"), { recursive: true })
  await writeFile(join(root, "src/style.css"), ":root {}\n", "utf-8")
  await writeFile(
    join(root, "vite.config.ts"),
    'import { defineConfig } from "vite";\nimport react from "@vitejs/plugin-react";\n\nexport default defineConfig({\n  plugins: [react()],\n});\n',
    "utf-8",
  )
}

describe("runUpdate", () => {
  let tempDir: string

  beforeEach(async () => {
    const testRoot = join(process.cwd(), ".tmp")
    await mkdir(testRoot, { recursive: true })
    tempDir = await mkdtemp(join(testRoot, "lexsys-cli-update-"))
    setCwd(tempDir)
    vi.spyOn(console, "log").mockImplementation(() => undefined)
  })

  afterEach(async () => {
    vi.restoreAllMocks()
    if (tempDir) {
      await rm(tempDir, { force: true, recursive: true })
    }
  })

  test("updates generated token and theme styles without requiring a component install", async () => {
    await writeJson(join(tempDir, "lexsys.config.json"), {
      style: "default",
      paths: {
        components: "src/components/ui",
        utilities: "src/lib",
        styles: "styles",
      },
      aliases: {
        components: "@/components/ui",
        ui: "@/components/ui",
        utils: "@/lib/utils",
        lib: "@/lib",
        hooks: "@/hooks",
      },
      tailwind: {
        version: "v4",
        css: "src/style.css",
      },
      installed: {},
    })
    await mkdir(join(tempDir, "src"), { recursive: true })
    await mkdir(join(tempDir, "styles"), { recursive: true })
    await writeFile(join(tempDir, "src/style.css"), ":root {}\n", "utf-8")
    await writeFile(
      join(tempDir, "styles/tokens.css"),
      `${generatedHeader}\n\n:root {\n  --lex-stale-token: true;\n}\n`,
      "utf-8",
    )
    await writeFile(
      join(tempDir, "styles/theme.css"),
      `${generatedHeader}\n\n:root {\n  --lex-stale-theme: true;\n}\n`,
      "utf-8",
    )

    await runUpdate(["--styles"])

    await expect(
      readFile(join(tempDir, "styles/tokens.css"), "utf-8"),
    ).resolves.toContain(`--${p}-toast-viewport-width`)
    await expect(
      readFile(join(tempDir, "styles/theme.css"), "utf-8"),
    ).resolves.toContain("@theme inline")
    await expect(
      readFile(join(tempDir, "src/style.css"), "utf-8"),
    ).resolves.toBe(
      '@import "../styles/tokens.css";\n' +
        '@import "../styles/theme.css";\n' +
        ":root {}\n",
    )
    expect(console.log).toHaveBeenCalledWith("Style update summary:")
  })

  test("sync refreshes same-version component templates with --force", async () => {
    await writeViteConsumerFiles(tempDir)
    await runInit()
    await runAdd(["button"])

    const buttonPath = join(tempDir, "src/components/ui/Button/Button.tsx")

    await writeFile(
      buttonPath,
      `${await readFile(buttonPath, "utf-8")}\n// stale local edit\n`,
      "utf-8",
    )

    await runUpdate(["button", "--sync"])

    await expect(readFile(buttonPath, "utf-8")).resolves.toContain(
      "stale local edit",
    )
    expect(console.log).toHaveBeenCalledWith(
      expect.stringContaining("template sync"),
    )

    await runUpdate(["button", "--sync", "--force"])

    await expect(readFile(buttonPath, "utf-8")).resolves.not.toContain(
      "stale local edit",
    )
  })

  test("utilities refresh overwrites stale utils.ts with --force", async () => {
    await writeViteConsumerFiles(tempDir)
    await runInit()
    await runAdd(["button"])

    const utilsPath = join(tempDir, "src/lib/utils.ts")
    const registryUtilsPath = getRegistryTemplatePath("shared/utils/cn.ts")

    await writeFile(utilsPath, "// stale utils\n", "utf-8")

    await runUpdate(["--utilities"])

    await expect(readFile(utilsPath, "utf-8")).resolves.toBe("// stale utils\n")
    expect(console.log).toHaveBeenCalledWith("Utility update summary:")

    await runUpdate(["--utilities", "--force"])

    await expect(readFile(utilsPath, "utf-8")).resolves.toBe(
      await readFile(registryUtilsPath, "utf-8"),
    )
    await expect(readFile(utilsPath, "utf-8")).resolves.toContain(
      "disabledStateClasses",
    )
  })

  test("combined sync utilities and styles refresh in one command", async () => {
    await writeViteConsumerFiles(tempDir)
    await runInit()
    await runAdd(["button"])

    await writeFile(
      join(tempDir, "styles/tokens.css"),
      `${generatedHeader}\n\n:root {\n  --lex-stale-token: true;\n}\n`,
      "utf-8",
    )
    await writeFile(
      join(tempDir, "src/lib/utils.ts"),
      "// stale utils\n",
      "utf-8",
    )

    await runUpdate(["--all", "--sync", "--utilities", "--styles", "--force"])

    await expect(
      readFile(join(tempDir, "styles/tokens.css"), "utf-8"),
    ).resolves.toContain(`--${p}-button-primary-background`)
    await expect(
      readFile(join(tempDir, "src/lib/utils.ts"), "utf-8"),
    ).resolves.toContain("disabledStateClasses")
  })
})
