import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises"
import { join } from "node:path"
import { afterEach, beforeEach, describe, expect, test, vi } from "vitest"
import { setCwd } from "../../src/core/context.js"
import { runUpdate } from "../../src/commands/update.js"

const generatedHeader =
  "/* Generated by @neurex/tokens. Do not edit directly. */"

const writeJson = async (path: string, value: unknown): Promise<void> => {
  await writeFile(path, JSON.stringify(value, null, 2) + "\n", "utf-8")
}

describe("runUpdate", () => {
  let tempDir: string

  beforeEach(async () => {
    const testRoot = join(process.cwd(), ".tmp")
    await mkdir(testRoot, { recursive: true })
    tempDir = await mkdtemp(join(testRoot, "neurex-cli-update-"))
    setCwd(tempDir)
    vi.spyOn(console, "log").mockImplementation(() => undefined)
  })

  afterEach(async () => {
    vi.restoreAllMocks()
    if (tempDir) {
      await rm(tempDir, { force: true, recursive: true })
    }
  })

  test("updates generated token and theme styles without requiring a component install", async () => {
    await writeJson(join(tempDir, "neurex.config.json"), {
      style: "default",
      componentsPath: "src/components/ui",
      utilitiesPath: "src/lib",
      stylesPath: "styles",
      tailwind: {
        version: "v4",
        css: "src/style.css",
      },
      installed: {},
    })
    await mkdir(join(tempDir, "src"), { recursive: true })
    await mkdir(join(tempDir, "styles"), { recursive: true })
    await writeFile(join(tempDir, "src/style.css"), ":root {}\n", "utf-8")
    await writeFile(
      join(tempDir, "styles/tokens.css"),
      `${generatedHeader}\n\n:root {\n  --nx-stale-token: true;\n}\n`,
      "utf-8",
    )
    await writeFile(
      join(tempDir, "styles/theme.css"),
      `${generatedHeader}\n\n:root {\n  --nx-stale-theme: true;\n}\n`,
      "utf-8",
    )

    await runUpdate(["--styles"])

    await expect(
      readFile(join(tempDir, "styles/tokens.css"), "utf-8"),
    ).resolves.toContain("--nx-toast-viewport-width")
    await expect(
      readFile(join(tempDir, "styles/theme.css"), "utf-8"),
    ).resolves.toContain("@theme inline")
    await expect(
      readFile(join(tempDir, "src/style.css"), "utf-8"),
    ).resolves.toBe(
      '@import "../styles/tokens.css";\n' +
        '@import "../styles/theme.css";\n' +
        ":root {}\n",
    )
    expect(console.log).toHaveBeenCalledWith("Style update summary:")
  })
})
