import { describe, expect, test } from "vitest"
import { createStyleOutputs } from "./outputs.js"

describe("createStyleOutputs", () => {
  test("generates token and theme css from token source", () => {
    const outputs = createStyleOutputs()

    expect(outputs.tokensCss).toContain(
      "Generated by @neurex-ui/tokens. Do not edit directly.",
    )
    expect(outputs.tokensCss).toContain("--nx-color-blue-600")
    expect(outputs.tokensCss).toContain("--nx-button-radius")

    expect(outputs.themeCss).toContain("--nx-color-background")
    expect(outputs.themeCss).toContain(".dark")
    expect(outputs.themeCss).toContain("@theme inline")
    expect(outputs.themeCss).toContain("--color-nx-primary")
  })
})
