import { componentTokens } from "./component-tokens.js"
import { primitiveTokens } from "./primitives.js"
import { semanticTokens } from "./semantic-tokens.js"
import { themes } from "./themes.js"
import type { StyleOutputs, TokenEntry } from "./types.js"

const header = "/* Generated by @neurex/tokens. Do not edit directly. */"

const toCustomProperty = (token: TokenEntry): string => {
  return `  --nx-${token.name}: ${token.value};`
}

const createRootBlock = (tokens: TokenEntry[]): string => {
  return [":root {", ...tokens.map(toCustomProperty), "}"].join("\n")
}

const createTokensCss = (): string => {
  const primitives = primitiveTokens.flatMap((group) => group.tokens)
  const semantics = semanticTokens.flatMap((group) => group.tokens)
  const componentValues = componentTokens.flatMap((group) => group.tokens)

  return `${header}\n\n${createRootBlock([...primitives, ...semantics, ...componentValues])}\n`
}

const createThemeBlock = (
  selector: string,
  colorScheme: string,
  tokens: Record<string, string>,
): string => {
  const tokenLines = Object.entries(tokens).map(([name, value]) => {
    return `  --nx-${name}: ${value};`
  })

  return [
    `${selector} {`,
    `  color-scheme: ${colorScheme};`,
    ...tokenLines,
    "}",
  ].join("\n")
}

const createTailwindThemeBlock = (): string => {
  const semanticNames = Object.keys(themes[0]?.tokens ?? {})
  const colorLines = semanticNames.map((name) => {
    const tailwindName = name.replace(/^color-/, "color-nx-")

    return `  --${tailwindName}: var(--nx-${name});`
  })

  const radiusLines = ["sm", "md", "lg", "xl", "full"].map((name) => {
    return `  --radius-nx-${name}: var(--nx-radius-${name});`
  })

  return ["@theme inline {", ...colorLines, ...radiusLines, "}"].join("\n")
}

const createThemeCss = (): string => {
  const themeBlocks = themes.map((theme) => {
    return createThemeBlock(theme.selector, theme.colorScheme, theme.tokens)
  })

  return `${header}\n\n${[...themeBlocks, createTailwindThemeBlock()].join("\n\n")}\n`
}

export const createStyleOutputs = (): StyleOutputs => {
  return {
    tokensCss: createTokensCss(),
    themeCss: createThemeCss(),
  }
}
