import {
  copyFile,
  mkdir,
  readFile,
  readdir,
  rm,
  unlink,
  writeFile,
} from "node:fs/promises"
import { dirname, join, relative } from "node:path"
import { fileURLToPath } from "node:url"
import type { RegistryItem } from "@lexsys/registry"
import type { LexsysConfig } from "./config.js"
import { prepareInstalledFileContent } from "./import-rewriter.js"
import { resolveItemInstallTarget } from "./install-target.js"
import { createBackupFile } from "./backup.js"
import { fileExists, filesAreEqual } from "./fs.js"
import { getCwd } from "./context.js"
import { fetchRemoteFile } from "./remote-files.js"
import { hashesAreEqual } from "./hash.js"
import type {
  ResolvedRegistryStyle,
  ResolvedRegistryUtility,
} from "./registry-types.js"
import { validateTemplateFiles } from "./template-validator.js"
import {
  createInstallResourceResult,
  hasInstallConflicts,
} from "./install-results.js"
import type { InstallResourceResult } from "./install-results.js"
import {
  createUninstallResourceResult,
  type UninstallResourceResult,
} from "./uninstall-results.js"

export const getRegistryTemplatePath = (templatePath: string): string => {
  const templateUrl = import.meta.resolve(
    `@lexsys/registry/templates/${templatePath}`,
  )

  return fileURLToPath(templateUrl)
}

const generatedStyleHeader =
  "/* Generated by @lexsys/tokens. Do not edit directly. */"

const isGeneratedLexsysStyle = (content: string): boolean => {
  return content.startsWith(generatedStyleHeader)
}

export const ensureProjectStructure = async (
  config: LexsysConfig,
): Promise<void> => {
  await mkdir(join(getCwd(), config.paths.components), { recursive: true })
  await mkdir(join(getCwd(), config.paths.utilities), { recursive: true })
  await mkdir(join(getCwd(), config.paths.styles), { recursive: true })
}

export const installUtilities = async (
  utilities: ResolvedRegistryUtility[],
  config: LexsysConfig,
): Promise<InstallResourceResult> => {
  const result = createInstallResourceResult()

  for (const utility of utilities) {
    const sourcePath = getRegistryTemplatePath(utility.path)
    const targetPath = join(getCwd(), config.paths.utilities, utility.target)

    await mkdir(dirname(targetPath), { recursive: true })

    if (await fileExists(targetPath)) {
      const isSameFile = await filesAreEqual(sourcePath, targetPath)

      if (isSameFile) {
        console.log(`Skipped identical utility: ${targetPath}`)
        result.skipped.push(targetPath)
        continue
      }

      console.log(`Conflict: utility already exists and differs: ${targetPath}`)
      result.conflicted.push(targetPath)
      continue
    }

    await copyFile(sourcePath, targetPath)
    console.log(`Created utility: ${targetPath}`)
    result.created.push(targetPath)
  }

  return result
}

export const updateUtilities = async (
  utilities: ResolvedRegistryUtility[],
  config: LexsysConfig,
  force: boolean,
): Promise<InstallResourceResult> => {
  const result = createInstallResourceResult()

  for (const utility of utilities) {
    const sourcePath = getRegistryTemplatePath(utility.path)
    const targetPath = join(getCwd(), config.paths.utilities, utility.target)

    await mkdir(dirname(targetPath), { recursive: true })

    if (!(await fileExists(targetPath))) {
      await copyFile(sourcePath, targetPath)
      console.log(`Created utility: ${targetPath}`)
      result.created.push(targetPath)
      continue
    }

    const isSameFile = await filesAreEqual(sourcePath, targetPath)

    if (isSameFile) {
      console.log(`Skipped identical utility: ${targetPath}`)
      result.skipped.push(targetPath)
      continue
    }

    if (force) {
      const backupPath = await createBackupFile(targetPath)

      if (backupPath) {
        console.log(`- backup created: ${backupPath}`)
      }

      await copyFile(sourcePath, targetPath)
      console.log(`Updated utility: ${targetPath}`)
      result.updated.push(targetPath)
      continue
    }

    console.log(`Conflict: utility already exists and differs: ${targetPath}`)
    result.conflicted.push(targetPath)
  }

  return result
}

export const installStyles = async (
  styles: ResolvedRegistryStyle[],
  config: LexsysConfig,
): Promise<InstallResourceResult> => {
  const result = createInstallResourceResult()
  const installedStyleTargets: string[] = []

  for (const style of styles) {
    console.log(`Installing style ${style.name}...`)

    for (const file of style.files) {
      const sourcePath = getRegistryTemplatePath(file.path)
      const targetPath = join(getCwd(), config.paths.styles, file.target)

      await mkdir(dirname(targetPath), { recursive: true })

      if (await fileExists(targetPath)) {
        const isSameFile = await filesAreEqual(sourcePath, targetPath)

        if (isSameFile) {
          console.log(`Skipped identical style: ${targetPath}`)
          result.skipped.push(targetPath)
          installedStyleTargets.push(file.target)
          continue
        }

        const sourceContent = await readFile(sourcePath, "utf-8")
        const targetContent = await readFile(targetPath, "utf-8")

        if (
          isGeneratedLexsysStyle(sourceContent) &&
          isGeneratedLexsysStyle(targetContent)
        ) {
          await writeFile(targetPath, sourceContent, "utf-8")
          console.log(`Updated generated style: ${targetPath}`)
          result.updated.push(targetPath)
          installedStyleTargets.push(file.target)
          continue
        }

        console.log(`Conflict: style already exists and differs: ${targetPath}`)
        result.conflicted.push(targetPath)
        continue
      }

      await copyFile(sourcePath, targetPath)
      console.log(`Created style: ${targetPath}`)
      result.created.push(targetPath)
      installedStyleTargets.push(file.target)
    }
  }

  if (!hasInstallConflicts(result) && installedStyleTargets.length) {
    const entrypointResult = await installStyleEntrypointImports(
      installedStyleTargets,
      config,
    )

    result.updated.push(...entrypointResult.updated)
    result.skipped.push(...entrypointResult.skipped)
  }

  return result
}

const toCssImportPath = (
  cssPath: string,
  styleTarget: string,
  config: LexsysConfig,
): string => {
  const importPath = relative(
    dirname(cssPath),
    join(config.paths.styles, styleTarget),
  ).replaceAll("\\", "/")

  return importPath.startsWith(".") ? importPath : `./${importPath}`
}

const getStyleImportInsertionIndex = (content: string): number => {
  const importHeaderMatch = content.match(
    /^(?:\s*@charset\s+["'][^"']+["'];\s*)?(?:\s*@import\s+[^;]+;\s*)*/u,
  )

  return importHeaderMatch?.[0].length ?? 0
}

const installStyleEntrypointImports = async (
  styleTargets: string[],
  config: LexsysConfig,
): Promise<Pick<InstallResourceResult, "updated" | "skipped">> => {
  const cssPath = join(getCwd(), config.tailwind.css)

  if (!(await fileExists(cssPath))) {
    console.log(
      `Skipped style wiring: Tailwind CSS entrypoint not found at ${cssPath}`,
    )
    return {
      skipped: [cssPath],
      updated: [],
    }
  }

  const content = await readFile(cssPath, "utf-8")
  const missingImports = styleTargets
    .map((styleTarget) =>
      toCssImportPath(config.tailwind.css, styleTarget, config),
    )
    .filter(
      (importPath) =>
        !content.includes(`"${importPath}"`) &&
        !content.includes(`'${importPath}'`),
    )
    .map((importPath) => `@import "${importPath}";`)

  if (!missingImports.length) {
    console.log(
      `Skipped style wiring: ${cssPath} already imports Lexsys styles`,
    )
    return {
      skipped: [cssPath],
      updated: [],
    }
  }

  const insertionIndex = getStyleImportInsertionIndex(content)
  const before = content.slice(0, insertionIndex)
  const after = content.slice(insertionIndex)
  const separator = before.endsWith("\n") || before.length === 0 ? "" : "\n"
  const updatedContent = `${before}${separator}${missingImports.join("\n")}\n${after}`

  await writeFile(cssPath, updatedContent, "utf-8")
  console.log(`Updated style entrypoint: ${cssPath}`)

  return {
    skipped: [],
    updated: [cssPath],
  }
}

const readPreparedTemplateContent = async (
  item: RegistryItem,
  file: string,
  remoteContent?: string,
): Promise<string> => {
  const rawContent =
    remoteContent ?? (await readFile(getRegistryTemplatePath(file), "utf-8"))

  return prepareInstalledFileContent(rawContent, item)
}

export const installItemFiles = async (
  item: RegistryItem,
  config: LexsysConfig,
): Promise<InstallResourceResult> => {
  const result = createInstallResourceResult()
  const installTarget = resolveItemInstallTarget(config, item)

  console.log(`Installing ${item.canonicalName}...\n`)

  await validateTemplateFiles(item)

  for (const file of item.files) {
    const remoteFile = item.remoteFiles?.find(
      (registryFile) => registryFile.path === file && registryFile.remoteUrl,
    )

    const fileName = file.split("/").at(-1)

    if (!fileName) {
      throw new Error(`Invalid registry file path: ${file}`)
    }

    const targetPath = join(getCwd(), installTarget, fileName)

    await mkdir(dirname(targetPath), { recursive: true })

    if (remoteFile?.remoteUrl) {
      console.log(`Fetching remote file: ${remoteFile.remoteUrl}`)

      const remoteContent = await fetchRemoteFile(remoteFile.remoteUrl)
      const preparedContent = await readPreparedTemplateContent(
        item,
        file,
        remoteContent,
      )

      if (await fileExists(targetPath)) {
        const targetContent = await readFile(targetPath, "utf-8")

        if (hashesAreEqual(preparedContent, targetContent)) {
          console.log(`Skipped identical file: ${targetPath}`)
          result.skipped.push(targetPath)
          continue
        }

        console.log(`Conflict: file already exists and differs: ${targetPath}`)
        result.conflicted.push(targetPath)
        continue
      }

      await writeFile(targetPath, preparedContent, "utf-8")
      console.log(`Created: ${targetPath}`)
      result.created.push(targetPath)
      continue
    }

    const preparedContent = await readPreparedTemplateContent(item, file)

    if (await fileExists(targetPath)) {
      const targetContent = await readFile(targetPath, "utf-8")

      if (hashesAreEqual(preparedContent, targetContent)) {
        console.log(`Skipped identical file: ${targetPath}`)
        result.skipped.push(targetPath)
        continue
      }

      console.log(`Conflict: file already exists and differs: ${targetPath}`)
      result.conflicted.push(targetPath)
      continue
    }

    await writeFile(targetPath, preparedContent, "utf-8")
    console.log(`Created: ${targetPath}`)
    result.created.push(targetPath)
  }

  console.log("\nDone.")

  return result
}

const removeFileIfMatchesTemplate = async (
  sourcePath: string,
  targetPath: string,
  result: UninstallResourceResult,
): Promise<void> => {
  if (!(await fileExists(targetPath))) {
    console.log(`Skipped missing file: ${targetPath}`)
    result.missing.push(targetPath)
    return
  }

  const isSameFile = await filesAreEqual(sourcePath, targetPath)

  if (!isSameFile) {
    console.log(`Conflict: file differs from registry template: ${targetPath}`)
    result.conflicted.push(targetPath)
    return
  }

  await unlink(targetPath)
  console.log(`Removed: ${targetPath}`)
  result.removed.push(targetPath)
}

const removeGeneratedStyleIfMatchesTemplate = async (
  sourcePath: string,
  targetPath: string,
  result: UninstallResourceResult,
): Promise<void> => {
  if (!(await fileExists(targetPath))) {
    console.log(`Skipped missing style: ${targetPath}`)
    result.missing.push(targetPath)
    return
  }

  const sourceContent = await readFile(sourcePath, "utf-8")
  const targetContent = await readFile(targetPath, "utf-8")

  if (
    isGeneratedLexsysStyle(sourceContent) &&
    isGeneratedLexsysStyle(targetContent) &&
    sourceContent === targetContent
  ) {
    await unlink(targetPath)
    console.log(`Removed generated style: ${targetPath}`)
    result.removed.push(targetPath)
    return
  }

  const isSameFile = await filesAreEqual(sourcePath, targetPath)

  if (isSameFile) {
    await unlink(targetPath)
    console.log(`Removed style: ${targetPath}`)
    result.removed.push(targetPath)
    return
  }

  console.log(`Conflict: style differs from registry template: ${targetPath}`)
  result.conflicted.push(targetPath)
}

const tryRemoveEmptyDirectory = async (
  directoryPath: string,
): Promise<void> => {
  try {
    const entries = await readdir(directoryPath)

    if (entries.length === 0) {
      await rm(directoryPath, { recursive: true })
      console.log(`Removed empty directory: ${directoryPath}`)
    }
  } catch {
    return
  }
}

export const uninstallItemFiles = async (
  item: RegistryItem,
  config: LexsysConfig,
): Promise<UninstallResourceResult> => {
  const result = createUninstallResourceResult()

  console.log(`Uninstalling ${item.canonicalName}...\n`)

  await validateTemplateFiles(item)

  const componentDirectory = join(
    getCwd(),
    resolveItemInstallTarget(config, item),
  )

  const plannedRemovals: string[] = []

  for (const file of item.files) {
    const fileName = file.split("/").at(-1)

    if (!fileName) {
      throw new Error(`Invalid registry file path: ${file}`)
    }

    const targetPath = join(componentDirectory, fileName)

    if (!(await fileExists(targetPath))) {
      console.log(`Skipped missing file: ${targetPath}`)
      result.missing.push(targetPath)
      continue
    }

    const preparedContent = await readPreparedTemplateContent(item, file)
    const targetContent = await readFile(targetPath, "utf-8")

    if (!hashesAreEqual(preparedContent, targetContent)) {
      console.log(
        `Conflict: file differs from registry template: ${targetPath}`,
      )
      result.conflicted.push(targetPath)
      continue
    }

    plannedRemovals.push(targetPath)
  }

  if (result.conflicted.length > 0) {
    console.log(
      "Skipped component file removal because one or more files differ from registry templates.",
    )
    console.log("\nDone.")
    return result
  }

  for (const targetPath of plannedRemovals) {
    await unlink(targetPath)
    console.log(`Removed: ${targetPath}`)
    result.removed.push(targetPath)
  }

  await tryRemoveEmptyDirectory(componentDirectory)

  console.log("\nDone.")

  return result
}

export const uninstallUtilities = async (
  utilities: ResolvedRegistryUtility[],
  config: LexsysConfig,
): Promise<UninstallResourceResult> => {
  const result = createUninstallResourceResult()

  for (const utility of utilities) {
    const sourcePath = getRegistryTemplatePath(utility.path)
    const targetPath = join(getCwd(), config.paths.utilities, utility.target)

    await removeFileIfMatchesTemplate(sourcePath, targetPath, result)
  }

  return result
}

export const uninstallStyles = async (
  styles: ResolvedRegistryStyle[],
  config: LexsysConfig,
): Promise<UninstallResourceResult> => {
  const result = createUninstallResourceResult()

  for (const style of styles) {
    console.log(`Uninstalling style ${style.name}...`)

    for (const file of style.files) {
      const sourcePath = getRegistryTemplatePath(file.path)
      const targetPath = join(getCwd(), config.paths.styles, file.target)

      await removeGeneratedStyleIfMatchesTemplate(
        sourcePath,
        targetPath,
        result,
      )
    }
  }

  return result
}
