import { describe, expect, test } from "vitest"
import { componentTokens } from "../src/components/index.js"
import { createStyleOutputs } from "../src/generators/outputs.js"
import { primitiveTokens } from "../src/primitives/index.js"
import { semanticTokens } from "../src/semantics/index.js"
import {
  defaultStylePresetId,
  neurexDefaultStylePreset,
  stylePresets,
} from "../src/styles/index.js"
import { themes } from "../src/themes/index.js"

describe("createStyleOutputs", () => {
  test("defines Neurex Default as the first style preset", () => {
    expect(defaultStylePresetId).toBe("default")
    expect(neurexDefaultStylePreset).toEqual({
      id: "default",
      name: "Neurex Default",
      description:
        "Baseline Neurex style preset for the initial token, theme, and component system.",
      themeModes: ["light", "dark"],
    })
    expect(stylePresets).toEqual([neurexDefaultStylePreset])
  })

  test("generates token and theme css from token source", () => {
    const outputs = createStyleOutputs()

    expect(outputs.tokensCss).toContain(
      "Generated by @neurex/tokens. Do not edit directly.",
    )
    expect(outputs.tokensCss).toContain("--nx-color-blue-600")
    expect(outputs.tokensCss).toContain(
      "--nx-radius-control: var(--nx-radius-md)",
    )
    expect(outputs.tokensCss).toContain(
      "--nx-space-surface-md: var(--nx-space-6)",
    )
    expect(outputs.tokensCss).toContain("--nx-button-radius")
    expect(outputs.tokensCss).toContain(
      "--nx-button-radius: var(--nx-radius-control)",
    )
    expect(outputs.tokensCss).toContain(
      "--nx-badge-radius: var(--nx-radius-control)",
    )
    expect(outputs.tokensCss).toContain(
      "--nx-badge-primary-background: var(--nx-color-primary)",
    )
    expect(outputs.tokensCss).toContain(
      "--nx-alert-radius: var(--nx-radius-surface)",
    )
    expect(outputs.tokensCss).toContain(
      "--nx-alert-destructive-foreground: var(--nx-color-destructive)",
    )
    expect(outputs.tokensCss).toContain(
      "--nx-card-background: var(--nx-color-surface)",
    )
    expect(outputs.tokensCss).toContain(
      "--nx-card-radius: var(--nx-radius-surface)",
    )
    expect(outputs.tokensCss).toContain(
      "--nx-checkbox-size-md: var(--nx-size-selection-control-md)",
    )
    expect(outputs.tokensCss).toContain(
      "--nx-switch-thumb-translate-md: var(--nx-size-switch-thumb-translate-md)",
    )
    expect(outputs.tokensCss).toContain(
      "--nx-tabs-tab-active-background: var(--nx-color-background)",
    )
    expect(outputs.tokensCss).toContain(
      "--nx-tooltip-background: var(--nx-color-foreground)",
    )

    expect(outputs.themeCss).toContain("--nx-color-background")
    expect(outputs.themeCss).toContain(".dark")
    expect(outputs.themeCss).toContain("@theme inline")
    expect(outputs.themeCss).toContain("--color-nx-primary")
  })

  test("keeps authoring tokens prefix-free", () => {
    const tokenSource = JSON.stringify({
      componentTokens,
      primitiveTokens,
      semanticTokens,
      themes,
    })

    expect(tokenSource).not.toContain("--nx")
    expect(tokenSource).not.toContain("var(--")
    expect(tokenSource).toContain("{motion.duration.fast}")
  })
})
