import { describe, expect, test } from "vitest"
import { componentTokens } from "../src/components/index.js"
import { createStyleOutputs } from "../src/generators/create-style-outputs.js"
import { createStyleTokenInput } from "../src/generators/input/index.js"
import { primitiveTokens } from "../src/primitives/index.js"
import { semanticTokens } from "../src/semantics/index.js"
import { neurexPreset, defaultPresetId, presets } from "../src/presets/index.js"
import { themes } from "../src/themes/index.js"

describe("createStyleOutputs", () => {
  test("assembles a W3C/DTCG-shaped generator input contract", () => {
    const input = createStyleTokenInput()

    expect(input.preset).toBe(neurexPreset)
    expect(input.foundationTokens.color).toBeDefined()
    expect(input.foundationTokens.radius).toBeDefined()
    expect(input.semanticTokens.color).toBeDefined()
    expect(input.semanticTokens.radius).toBeDefined()
    expect(input.componentTokens.button).toBeDefined()
    expect(input.tokenTree.button).toBe(input.componentTokens.button)
    expect(input.themeTokens[0]).toMatchObject({
      name: "light",
      selector: ":root",
      colorScheme: "light",
      brand: "neurex",
    })
    expect(input.themeTokens[0]?.tokens.color).toBeDefined()
  })

  test("uses one active preset when assembling generator input", () => {
    const input = createStyleTokenInput({
      presetId: "neurex",
    })

    expect(input.preset.id).toBe("neurex")
    expect(input.themeTokens.map((theme) => theme.name)).toEqual([
      "light",
      "dark",
    ])
  })

  test("defines Neurex Default as the first style preset", () => {
    expect(defaultPresetId).toBe("neurex")

    expect(neurexPreset).toEqual({
      id: "neurex",
      name: "Neurex Default",
      brand: "neurex",
      description:
        "Baseline Neurex style preset for the initial token, theme, and component system.",
      themeModes: ["light", "dark"],
      defaultTheme: "light",
    })
    expect(presets).toEqual([neurexPreset])
  })

  test("generates token and theme css from token source", () => {
    const outputs = createStyleOutputs()

    expect(outputs.tokensCss).toContain(
      "Generated by @neurex/tokens. Do not edit directly.",
    )
    expect(outputs.tokensCss).toContain("--nx-color-blue-600")
    expect(outputs.tokensCss).toContain(
      "--nx-radius-control: var(--nx-radius-md)",
    )
    expect(outputs.tokensCss).toContain(
      "--nx-space-surface-md: var(--nx-space-6)",
    )
    expect(outputs.tokensCss).toContain("--nx-line-height-normal: 1.5")
    expect(outputs.tokensCss).not.toContain("--nx-line-height-6")
    expect(outputs.tokensCss).toContain(
      "--nx-button-radius: var(--nx-radius-control)",
    )
    expect(outputs.tokensCss).toContain(
      "--nx-badge-radius: var(--nx-radius-control)",
    )
    expect(outputs.tokensCss).toContain(
      "--nx-badge-primary-background: var(--nx-color-action-primary-base)",
    )
    expect(outputs.tokensCss).toContain(
      "--nx-alert-radius: var(--nx-radius-surface)",
    )
    expect(outputs.tokensCss).toContain(
      "--nx-alert-destructive-foreground: var(--nx-color-action-danger-base)",
    )
    expect(outputs.tokensCss).toContain(
      "--nx-card-background: var(--nx-color-background-surface)",
    )
    expect(outputs.tokensCss).toContain(
      "--nx-card-radius: var(--nx-radius-surface)",
    )
    expect(outputs.tokensCss).toContain(
      "--nx-checkbox-size-md: var(--nx-size-selection-control-md)",
    )
    expect(outputs.tokensCss).toContain(
      "--nx-switch-thumb-translate-md: var(--nx-size-switch-thumb-translate-md)",
    )
    expect(outputs.tokensCss).toContain(
      "--nx-tabs-tab-active-background: var(--nx-color-background-base)",
    )
    expect(outputs.tokensCss).toContain(
      "--nx-tooltip-background: var(--nx-color-text-primary)",
    )

    expect(outputs.themeCss).toContain("--nx-color-background-base")
    expect(outputs.themeCss).toContain(".dark")
    expect(outputs.themeCss).toContain("@theme inline")
    expect(outputs.themeCss).toContain("--color-nx-action-primary-base")
    expect(outputs.themeCss).toContain("--color-nx-background-base")
    expect(outputs.themeCss).toContain("--radius-nx-control")
    expect(outputs.themeCss).toContain("--spacing-nx-surface-md")
    expect(outputs.themeCss).toContain("--duration-nx-control")
    expect(outputs.themeCss).toContain("--ease-nx-control")
    expect(outputs.themeCss).not.toContain("--color-nx-color-")
  })

  test("generates DTCG-compatible token json from token source", () => {
    const outputs = createStyleOutputs()
    const json = JSON.parse(outputs.tokensJson) as {
      color?: {
        blue?: {
          "600"?: {
            $value?: unknown
            $type?: unknown
          }
        }
      }
      button?: {
        radius?: {
          $value?: unknown
          $type?: unknown
        }
      }
      "line-height"?: {
        normal?: {
          $value?: unknown
          $type?: unknown
        }
      }
    }

    expect(json.color?.blue?.["600"]).toEqual({
      $value: "oklch(0.455 0.191 259.631)",
      $type: "color",
    })
    expect(json.button?.radius).toEqual({
      $value: "{radius.control}",
      $type: "dimension",
    })
    expect(json["line-height"]?.normal).toEqual({
      $value: 1.5,
      $type: "number",
    })
  })

  test("keeps authoring tokens prefix-free", () => {
    const tokenSource = JSON.stringify({
      componentTokens,
      primitiveTokens,
      semanticTokens,
      themes,
    })

    expect(tokenSource).not.toContain("--nx")
    expect(tokenSource).not.toContain("var(--")
    expect(tokenSource).not.toContain("{line-height.6}")
    expect(tokenSource).toContain("{motion.duration.fast}")
  })
})
