import { describe, expect, test } from "vitest"
import { createStyleOutputs } from "../src/outputs.js"
import {
  defaultStylePresetId,
  neurexDefaultStylePreset,
  stylePresets,
} from "../src/styles/index.js"

describe("createStyleOutputs", () => {
  test("defines Neurex Default as the first style preset", () => {
    expect(defaultStylePresetId).toBe("default")
    expect(neurexDefaultStylePreset).toEqual({
      id: "default",
      name: "Neurex Default",
      description:
        "Baseline Neurex style preset for the initial token, theme, and component system.",
      themeModes: ["light", "dark"],
    })
    expect(stylePresets).toEqual([neurexDefaultStylePreset])
  })

  test("generates token and theme css from token source", () => {
    const outputs = createStyleOutputs()

    expect(outputs.tokensCss).toContain(
      "Generated by @neurex/tokens. Do not edit directly.",
    )
    expect(outputs.tokensCss).toContain("--nx-color-blue-600")
    expect(outputs.tokensCss).toContain("--nx-button-radius")

    expect(outputs.themeCss).toContain("--nx-color-background")
    expect(outputs.themeCss).toContain(".dark")
    expect(outputs.themeCss).toContain("@theme inline")
    expect(outputs.themeCss).toContain("--color-nx-primary")
  })
})
