/**
 * style-output.config.ts
 *
 * @layer generators
 * @description Shared configuration for generated style outputs.
 *
 * @responsibility
 * - Define output-only CSS generation settings
 * - Keep generated CSS naming separate from token authoring
 *
 * @notes
 * - The CSS variable prefix belongs only to generated output.
 * - Token source files must not include the generated CSS prefix.
 */

export interface StyleOutputConfig {
  cssVarPrefix: string
  tailwindPrefix: string
  registryStylesPath: string
  styleHeader: string
  groupNameOverrides: Readonly<Record<string, string>>
  tailwindThemeNamespaces: Readonly<Record<string, string>>
}

export const defaultStyleOutputConfig: StyleOutputConfig = {
  cssVarPrefix: "lex",
  tailwindPrefix: "twix",
  registryStylesPath: "packages/registry/templates/styles",
  styleHeader:
    "/* Generated by @dalexto/lexsys-tokens. Do not edit directly. */",
  groupNameOverrides: {
    spacing: "space",
    "motion-duration": "duration",
    "motion-easing": "easing",
  },
  tailwindThemeNamespaces: {
    color: "color",
    duration: "duration",
    easing: "ease",
    radius: "radius",
    size: "spacing",
    space: "spacing",
    typography: "text",
  },
}
