/**
 * style-output.config.ts
 *
 * @layer generators
 * @description Shared configuration for generated style outputs.
 *
 * @responsibility
 * - Define output-only CSS generation settings
 * - Keep generated CSS naming separate from token authoring
 *
 * @notes
 * - The CSS variable prefix belongs only to generated output.
 * - Token source files must not include the generated CSS prefix.
 */

/** Stable prefix used by the CLI to detect generated style files. */
export const generatedStyleFileHeader = `/**
 * AUTO-GENERATED FILE.
 *
 * Generated by @dalexto/lexsys-tokens.
 * Manual changes will be overwritten.
`

export const createGeneratedStyleFileHeader = (
  generatedAt: Date = new Date(),
): string => {
  return `${generatedStyleFileHeader} * Last generated: ${generatedAt.toISOString()}
 */`
}

export interface StyleOutputConfig {
  cssVarPrefix: string
  tailwindPrefix: string
  registryStylesPath: string
  groupNameOverrides: Readonly<Record<string, string>>
  tailwindThemeNamespaces: Readonly<Record<string, string>>
}

export const defaultStyleOutputConfig: StyleOutputConfig = {
  cssVarPrefix: "lex",
  tailwindPrefix: "twix",
  registryStylesPath: "packages/registry/templates/styles",
  groupNameOverrides: {
    spacing: "space",
    "motion-duration": "duration",
    "motion-easing": "easing",
  },
  tailwindThemeNamespaces: {
    color: "color",
    duration: "duration",
    easing: "ease",
    radius: "radius",
    size: "spacing",
    space: "spacing",
    typography: "text",
  },
}
