/**
 * style-output.config.ts
 *
 * @layer generators
 * @description Shared configuration for generated style outputs.
 *
 * @responsibility
 * - Define output-only CSS generation settings
 * - Keep generated CSS naming separate from token authoring
 *
 * @notes
 * - The CSS variable prefix belongs only to generated output.
 * - Token source files must not include the generated CSS prefix.
 */

export interface StyleOutputConfig {
  cssVarPrefix: string
  tailwindPrefix: string
  styleHeader: string
  groupNameOverrides: Readonly<Record<string, string>>
}

export const defaultStyleOutputConfig: StyleOutputConfig = {
  cssVarPrefix: "nx",
  tailwindPrefix: "nx",
  styleHeader: "/* Generated by @neurex/tokens. Do not edit directly. */",
  groupNameOverrides: {
    spacing: "space",
    "motion-duration": "duration",
    "motion-easing": "easing",
  },
}
