import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises"
import { join } from "node:path"
import { afterEach, beforeEach, describe, expect, test } from "vitest"
import {
  buttonRegistryItem,
  themeRegistryStyle,
} from "@dalexto/lexsys-registry"
import type { LexsysConfig } from "../../src/config/config.js"
import { setCwd } from "../../src/utils/context.js"
import {
  getRegistryTemplatePath,
  installItemFiles,
  installStyles,
} from "../../src/install/installer.js"
import { testCssVarPrefix as p } from "../config/prefix.js"

const config: LexsysConfig = {
  style: "default",
  paths: {
    components: "src/components/ui",
    utilities: "src/lib",
    styles: "styles",
  },
  aliases: {
    components: "@/components/ui",
    ui: "@/components/ui",
    utils: "@/lib/utils",
    lib: "@/lib",
    hooks: "@/hooks",
  },
  tailwind: {
    version: "v4",
    css: "src/style.css",
  },
  installed: [] as string[],
  registryUrl: null,
}

describe("installItemFiles", () => {
  let tempDir: string

  beforeEach(async () => {
    const testRoot = join(process.cwd(), ".tmp")
    await mkdir(testRoot, { recursive: true })
    tempDir = await mkdtemp(join(testRoot, "lexsys-cli-installer-"))
    setCwd(tempDir)
  })

  afterEach(async () => {
    if (tempDir) {
      await rm(tempDir, { force: true, recursive: true })
    }
  })

  test("reports conflicts without overwriting user-modified files", async () => {
    const targetDir = join(tempDir, "src/components/ui/Button")
    const targetPath = join(targetDir, "Button.tsx")

    await mkdir(targetDir, { recursive: true })
    await writeFile(targetPath, "user modified", "utf-8")

    const result = await installItemFiles(buttonRegistryItem, config)

    await expect(readFile(targetPath, "utf-8")).resolves.toBe("user modified")
    expect(result.conflicted).toContain(targetPath)
    expect(result.created).toHaveLength(2)
  })

  test("resolves registry templates through package exports", async () => {
    const templatePath = getRegistryTemplatePath("primitives/Button/Button.tsx")

    await expect(readFile(templatePath, "utf-8")).resolves.toContain(
      "export { Button }",
    )
  })

  test("installs registry styles without overwriting conflicts", async () => {
    const targetDir = join(tempDir, "styles")
    const targetPath = join(targetDir, "theme.css")

    await mkdir(targetDir, { recursive: true })
    await writeFile(targetPath, "user theme", "utf-8")

    const result = await installStyles([themeRegistryStyle], config)

    await expect(readFile(targetPath, "utf-8")).resolves.toBe("user theme")
    expect(result.created).toHaveLength(1)
    expect(result.created[0]).toContain("tokens.css")
    expect(result.conflicted).toEqual([targetPath])
  })

  test("updates existing generated registry styles", async () => {
    const targetDir = join(tempDir, "styles")
    const targetPath = join(targetDir, "tokens.css")
    const generatedHeader =
      "/* Generated by @dalexto/lexsys-tokens. Do not edit directly. */"

    await mkdir(targetDir, { recursive: true })
    await writeFile(
      targetPath,
      `${generatedHeader}\n\n:root {\n  --lex-button-radius: var(--lex-radius-md);\n}\n`,
      "utf-8",
    )

    const result = await installStyles([themeRegistryStyle], config)

    await expect(readFile(targetPath, "utf-8")).resolves.toContain(
      `--${p}-badge-radius`,
    )
    expect(result.updated).toContain(targetPath)
    expect(result.created.some((path) => path.endsWith("theme.css"))).toBe(true)
  })

  test("wires installed styles into the configured Tailwind CSS entrypoint", async () => {
    const cssPath = join(tempDir, "src/style.css")

    await mkdir(join(tempDir, "src"), { recursive: true })
    await writeFile(cssPath, ":root {\n  color: black;\n}\n", "utf-8")

    const firstResult = await installStyles([themeRegistryStyle], config)
    const secondResult = await installStyles([themeRegistryStyle], config)

    await expect(readFile(cssPath, "utf-8")).resolves.toBe(
      '@import "../styles/tokens.css";\n' +
        '@import "../styles/theme.css";\n' +
        ":root {\n" +
        "  color: black;\n" +
        "}\n",
    )
    expect(firstResult.updated).toEqual([cssPath])
    expect(secondResult.skipped).toContain(cssPath)
  })
})
